#!/bin/bash

## This file is part of hardened-tumbleweed <https://github.com/monsieuremre/hardened-tumbleweed>
## hardened-tumbleweed is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
## License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
## version. hardened-tumbleweed is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
## implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
## details. You should have received a copy of the GNU General Public License along with this program. If not, see
## <https://www.gnu.org/licenses/>.

echo "Applying system hardening..."

bash scripts/banner-issue.sh
bash scripts/firewall.sh
bash scripts/harden-fstab.sh
bash scripts/install-config-files.sh
bash scripts/login-defs.sh
bash scripts/parm-harden.sh
bash scripts/user-homes.sh
bash scripts/zypper.sh
bash scripts/entropy.sh
bash scripts/usb-guard.sh
bash scripts/protect_grub.sh
bash scripts/reload.sh
clear

echo "System hardening options have been applied."
