#!/bin/bash

## This file is part of hardened-tumbleweed <https://github.com/monsieuremre/hardened-tumbleweed>
## hardened-tumbleweed is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
## License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
## version. hardened-tumbleweed is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
## implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
## details. You should have received a copy of the GNU General Public License along with this program. If not, see
## <https://www.gnu.org/licenses/>.

echo "Applying system hardening..."

if [ ! -d /etc/hardened_tumbleweed ]
then
  mkdir /etc/hardened_tumbleweed
fi

echo "Hardening system banners..."
bash scripts/banner-issue.sh
echo "Hardening firewall configuration..."
bash scripts/firewall.sh
echo "Hardening mount options..."
bash scripts/harden-fstab.sh
echo "Hardening config files..."
bash scripts/install-config-files.sh
echo "Hardening login-defs..."
bash scripts/login-defs.sh
echo "Hardening pam..."
bash scripts/pam-harden.sh
echo "Hardening user home directories..."
bash scripts/user-homes.sh
echo "Hardening zypper..."
bash scripts/zypper.sh
echo "Improving entropy..."
bash scripts/entropy.sh
echo "Installing and setting usb-guard..."
bash scripts/usb-guard.sh
echo "Protecting grub..."
bash scripts/protect_grub.sh
echo "Reloading..."
bash scripts/reload.sh
clear

echo "System hardening options have been applied."
